var STORE='minecraft-hub.servers.v1',HOME_STORE='minecraft-hub.home-server.v1',state={items:[],last:null,home:null};function $(id){return document.getElementById(id)}function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}async function note(m,t){try{await Tapp.ui.showNotification({title:t==='error'?'查询失败':'Minecraft',message:m,type:t||'success',duration:3000})}catch(e){}}function validAddress(v){return /^[a-z0-9.-]+(?::\d{1,5})?$/i.test(v)&&!/^[-.:]|[-.:]$/.test(v)}function motd(x){if(!x)return'';if(typeof x==='string')return x;if(Array.isArray(x.clean))return x.clean.join('\n');return x.clean||x.raw||''}
function applyTheme(t){var d=t===true||t==='dark'||t==='Dark';document.documentElement.classList.toggle('dark',d)}async function theme(){try{var t=Tapp.ui.getTheme();applyTheme(t&&typeof t.then==='function'?await t:t);Tapp.ui.onThemeChange(applyTheme)}catch(e){}}
function apiData(v){return v&&v.success===true&&Object.prototype.hasOwnProperty.call(v,'data')?v.data:v}
async function load(){state.items=await Tapp.storage.get(STORE)||[];state.home=await Tapp.storage.get(HOME_STORE)||null;renderSaved()}async function persist(){await Tapp.storage.set(STORE,state.items.slice(0,30))}
function remember(address,edition,data){var old=state.items.find(function(x){return x.address===address&&x.edition===edition}),favorite=old&&old.favorite;state.items=state.items.filter(function(x){return!(x.address===address&&x.edition===edition)});state.items.unshift({address:address,edition:edition,favorite:!!favorite,online:!!data.online,players:data.players&&data.players.online||0,checked:new Date().toISOString()});persist();renderSaved()}
function playerNames(data){var list=data.players&&data.players.list||[];return list.map(function(x){return typeof x==='string'?x:x.name}).filter(Boolean)}
function renderServer(data,address,edition){var box=$('server-result');box.className='panel result '+(data.online?'online':'offline');if(!data.online){box.innerHTML='<div class="status-line"><span class="dot"></span><b>服务器离线或无法访问</b></div><h2>'+esc(address)+'</h2><p class="muted">请确认版本类型、地址和端口是否正确。查询服务可能缓存结果约 5 分钟。</p>';return}var players=data.players||{},names=playerNames(data),icon=data.icon?'<img class="server-icon" src="'+esc(data.icon)+'" alt="">':'<div class="server-icon fallback">⛏</div>';box.innerHTML='<div class="server-top">'+icon+'<div><div class="status-line"><span class="dot"></span><b>在线</b><span class="edition">'+(edition==='java'?'Java':'基岩版')+'</span></div><h2>'+esc(data.hostname||address)+'</h2><p class="motd">'+esc(motd(data.motd))+'</p></div><div class="server-actions"><button id="favorite-btn">☆ 收藏</button><button id="home-server-btn" class="primary">设为首页展示</button></div></div><div class="stats"><div><span>在线玩家</span><strong>'+esc(players.online||0)+' / '+esc(players.max||'?')+'</strong></div><div><span>版本</span><strong>'+esc(data.version||data.protocol&&data.protocol.name||'未知')+'</strong></div><div><span>软件</span><strong>'+esc(data.software||'Vanilla / 未知')+'</strong></div><div><span>地址</span><strong>'+esc((data.ip||address)+':'+(data.port||''))+'</strong></div></div>'+(names.length?'<div class="players"><h3>可见玩家</h3>'+names.map(function(n){return'<span>'+esc(n)+'</span>'}).join('')+'</div>':'');$('favorite-btn').onclick=function(){toggleFavorite(address,edition)};$('home-server-btn').onclick=function(){setHomeServer(address,edition,data)}}
async function query(){var address=$('address').value.trim(),edition=$('edition').value;if(!validAddress(address))return note('请输入有效的域名/IP，可附带端口','error');$('server-result').innerHTML='<div class="loading">正在连接方块世界…</div>';try{var params={address:encodeURIComponent(address)},response=edition==='java'?await Tapp.api('javaStatus',params):await Tapp.api('bedrockStatus',params),data=apiData(response);state.last={address:address,edition:edition,data:data};renderServer(data,address,edition);remember(address,edition,data)}catch(e){$('server-result').innerHTML='<div class="empty-state"><h2>查询失败</h2><p>'+esc(e.message||e)+'</p></div>';note(e.message||String(e),'error')}}
function fillHomeSettings(){if(!$('home-address'))return;$('home-address').value=state.home&&state.home.address||'';$('home-edition').value=state.home&&state.home.edition||'java';$('home-server-status').textContent=state.home?'当前展示：'+state.home.address:'尚未设置'}
async function setHomeServer(address,edition,data){state.home={address:address,edition:edition,data:data||null,updated:new Date().toISOString()};await Tapp.storage.set(HOME_STORE,state.home);fillHomeSettings();note('已设为首页小组件展示服务器','success')}
async function saveHomeSettings(){var address=$('home-address').value.trim(),edition=$('home-edition').value;if(!validAddress(address))return note('请输入有效的服务器域名/IP，可附带端口','error');var button=$('save-home-server');button.disabled=true;button.textContent='正在验证…';try{var params={address:encodeURIComponent(address)},response=edition==='bedrock'?await Tapp.api('bedrockStatus',params):await Tapp.api('javaStatus',params),data=apiData(response);await setHomeServer(address,edition,data)}catch(e){await setHomeServer(address,edition,null)}finally{button.disabled=false;button.textContent='保存展示服务器'}}
async function toggleFavorite(address,edition){var x=state.items.find(function(i){return i.address===address&&i.edition===edition});if(!x)return;x.favorite=!x.favorite;await persist();renderSaved();if(state.last&&state.last.address===address)renderServer(state.last.data,address,edition);note(x.favorite?'已收藏服务器':'已取消收藏','success')}
function renderSaved(){var b=$('saved-list');if(!b)return;if(!state.items.length){b.innerHTML='<p class="muted">暂无查询记录</p>';return}var a=state.items.slice().sort(function(x,y){return Number(y.favorite)-Number(x.favorite)});b.innerHTML=a.map(function(x){return'<button class="saved-item" data-address="'+esc(x.address)+'" data-edition="'+x.edition+'"><span class="dot '+(x.online?'on':'')+'"></span><div><b>'+(x.favorite?'★ ':'')+esc(x.address)+'</b><small>'+(x.edition==='java'?'Java':'基岩版')+' · '+x.players+' 人在线</small></div><time>'+new Date(x.checked).toLocaleString()+'</time></button>'}).join('');b.querySelectorAll('.saved-item').forEach(function(btn){btn.onclick=function(){$('address').value=btn.dataset.address;$('edition').value=btn.dataset.edition;switchTab('server');query()}})}
function copyText(v){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(v);var t=document.createElement('textarea');t.value=v;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();return Promise.resolve()}
async function searchWiki(){var q=$('wiki-query').value.trim();if(!q)return note('请输入 Wiki 关键词','error');var b=$('wiki-results');b.innerHTML='<div class="panel loading">正在翻阅 Wiki…</div>';try{var r=apiData(await Tapp.api('wikiSearch',{query:encodeURIComponent(q)})),pages=r&&r.query&&r.query.pages||[],list=Array.isArray(pages)?pages:Object.keys(pages).map(function(k){return pages[k]});list.sort(function(a,b){return(a.index||0)-(b.index||0)});if(!list.length){b.innerHTML='<div class="panel empty-state">没有找到相关条目</div>';return}b.innerHTML=list.map(function(x){var url='https://zh.minecraft.wiki/w/'+encodeURIComponent(String(x.title).replace(/ /g,'_'));return'<button class="wiki-card" data-url="'+esc(url)+'"><h3>'+esc(x.title)+'</h3><p>'+esc(x.extract||'暂无摘要')+'</p><span>复制条目地址 →</span></button>'}).join('');b.querySelectorAll('.wiki-card').forEach(function(x){x.onclick=function(){copyText(x.dataset.url).then(function(){note('Wiki 地址已复制，请在浏览器打开','success')})}})}catch(e){b.innerHTML='<div class="panel empty-state">Wiki 查询失败：'+esc(e.message||e)+'</div>'}}
function switchTab(name){document.querySelectorAll('.tab-panel').forEach(function(x){x.hidden=x.id!==name+'-tab'});document.querySelectorAll('[data-tab]').forEach(function(x){x.classList.toggle('active',x.dataset.tab===name)})}
async function init(){await theme();await load();fillHomeSettings();document.querySelectorAll('[data-tab]').forEach(function(x){x.onclick=function(){switchTab(x.dataset.tab)}});$('query-btn').onclick=query;$('address').onkeydown=function(e){if(e.key==='Enter')query()};$('wiki-btn').onclick=searchWiki;$('wiki-query').onkeydown=function(e){if(e.key==='Enter')searchWiki()};$('save-home-server').onclick=saveHomeSettings;$('home-address').onkeydown=function(e){if(e.key==='Enter')saveHomeSettings()};$('clear-history').onclick=async function(){state.items=[];await persist();renderSaved()}}
function widgetMotd(data){return motd(data&&data.motd)||'暂无服务器介绍'}
function renderHomeWidget(config,data,error){var root=$('mc-widget');if(!root)return;var empty=$('widget-empty'),content=$('widget-content');if(!config){empty.hidden=false;content.hidden=true;return}empty.hidden=true;content.hidden=false;$('widget-address').textContent=config.address;$('widget-edition').textContent=config.edition==='java'?'JAVA':'BEDROCK';var online=!!(data&&data.online),status=$('widget-status');status.textContent=error?'查询失败':online?'在线':'离线';status.className='widget-status '+(online?'online':'offline');$('widget-players').textContent=online?String(data.players&&data.players.online||0)+' / '+String(data.players&&data.players.max||'?'):'—';$('widget-version').textContent=online?String(data.version||data.protocol&&data.protocol.name||'未知'):'—';$('widget-motd').textContent=online?widgetMotd(data):(error||'服务器当前离线')}
async function initWidget(){var config=null;try{var props=window._TAPP_WIDGET_PROPS||{};applyTheme(props.theme);config=await Tapp.storage.get(HOME_STORE);if(!config){renderHomeWidget(null);return}renderHomeWidget(config,config.data);var params={address:encodeURIComponent(config.address)},response=config.edition==='bedrock'?await Tapp.api('bedrockStatus',params):await Tapp.api('javaStatus',params),data=apiData(response);config.data=data;config.updated=new Date().toISOString();await Tapp.storage.set(HOME_STORE,config);renderHomeWidget(config,data)}catch(e){renderHomeWidget(config,config&&config.data,e.message||String(e))}}
(function(){if(window._TAPP_MODE==='widget'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initWidget);else setTimeout(initWidget,0)}else if(window._TAPP_MODE==='page'||window._TAPP_HAS_HTML)Tapp.lifecycle.onReady(init)})();